// @mimir/graphql-schema — exports the SDL path for codegen consumers.
// The actual schema.graphql is auto-generated by apps/api on build (MM-006).
// DO NOT edit schema.graphql by hand — see CLAUDE.md §3.

import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));

export const SCHEMA_PATH = path.resolve(here, '../schema.graphql');
