// AUTO-GENERATED by `pnpm --filter mobile codegen` — do not edit by hand.
// This file is overwritten on every codegen run.
//
// MM-007 ships an empty placeholder so mobile compiles before the first codegen
// invocation. Run `pnpm codegen` from the repo root after `pnpm install` to
// regenerate this with typed Apollo hooks for ./graphql/operations/*.graphql.

export {};
