// Top NSE symbols by market cap — hardcoded for Phase 1, refreshed weekly in Phase 2.
// Source: NSE India top 100 constituents (NIFTY 100 index).
// MM-021: used by MarketDataPoller to determine which symbols to poll each tick.

export const TOP_100_NSE_SYMBOLS = [
  // NIFTY 50
  'RELIANCE', 'TCS', 'HDFCBANK', 'ICICIBANK', 'INFY',
  'HINDUNILVR', 'ITC', 'SBIN', 'BHARTIARTL', 'KOTAKBANK',
  'LT', 'AXISBANK', 'ASIANPAINT', 'MARUTI', 'TITAN',
  'BAJFINANCE', 'HCLTECH', 'SUNPHARMA', 'WIPRO', 'ULTRACEMCO',
  'NESTLEIND', 'POWERGRID', 'NTPC', 'TECHM', 'TATASTEEL',
  'INDUSINDBK', 'JSWSTEEL', 'BAJAJFINSV', 'ADANIENT', 'ADANIPORTS',
  'ONGC', 'COALINDIA', 'DIVISLAB', 'DRREDDY', 'CIPLA',
  'EICHERMOT', 'HEROMOTOCO', 'M&M', 'TATACONSUM', 'APOLLOHOSP',
  'BPCL', 'BRITANNIA', 'GRASIM', 'HINDALCO', 'SBILIFE',
  'HDFCLIFE', 'BAJAJ-AUTO', 'TATAMOTORS', 'UPL', 'LTIM',

  // NIFTY NEXT 50 additions
  'PIDILITIND', 'HAVELLS', 'BERGEPAINT', 'DABUR', 'GODREJCP',
  'MARICO', 'COLPAL', 'MCDOWELL-N', 'TRENT', 'DMART',
  'BOSCHLTD', 'SIEMENS', 'ABB', 'CUMMINSIND', 'GLAXO',
  'TORNTPHARM', 'LUPIN', 'BIOCON', 'AUROPHARMA', 'MUTHOOTFIN',
  'CHOLAFIN', 'SHRIRAMFIN', 'BAJAJHLDNG', 'SBICARD', 'BANDHANBNK',
  'PEL', 'NAUKRI', 'INDIGO', 'ADANIGREEN', 'ADANITRANS',
  'TATAPOWER', 'IRCTC', 'HAL', 'BEL', 'BHEL',
  'SAIL', 'NMDC', 'GAIL', 'IOC', 'HPCL',
  'VEDL', 'HINDZINC', 'NATIONALUM', 'MOIL', 'RECLTD',
  'PFC', 'IDFCFIRSTB', 'FEDERALBNK', 'RBLBANK', 'EXIDEIND',
] as const;

export type NseSymbol = (typeof TOP_100_NSE_SYMBOLS)[number];
