// PlaceOrderInput — @InputType mirroring the shared Zod schema.
// Prompt 07 (how-to-design-a-dto): class-validator decorators match the Zod schema
// in @mimir/shared so backend validation is consistent with mobile-side validation.
// Prompt 24 (graphql-resolver): @InputType lives in dto/, not inline in resolver.

import { ORDER_TYPES } from '@mimir/shared';
import { Field, InputType, Int } from '@nestjs/graphql';
import { IsIn, IsInt, IsString, IsUUID, Matches, Max, Min } from 'class-validator';


@InputType({ description: 'Input for placing a simulated market order (BUY or SELL).' })
export class PlaceOrderInput {
  @Field({ description: 'NSE symbol, e.g. RELIANCE, TCS.NS.' })
  @IsString()
  @Matches(/^[A-Z0-9.-]+$/, { message: 'NSE-style symbol expected (uppercase A-Z, digits, dot, dash)' })
  symbol!: string;

  @Field({ description: 'BUY or SELL.' })
  @IsIn([ORDER_TYPES.BUY, ORDER_TYPES.SELL])
  type!: string;

  @Field(() => Int, { description: 'Number of shares. Min 1, max 1,000,000.' })
  @IsInt()
  @Min(1)
  @Max(1_000_000)
  quantity!: number;

  @Field({
    description:
      'UUID v4 generated by mobile before the call. ' +
      'Used for idempotency: submitting the same ID twice returns the existing order.',
  })
  @IsUUID('4')
  clientGeneratedOrderId!: string;
}
